name: Despliegue Continuo

on:
  push:
    branches:
      - master  # Cambia esto si tu rama principal se llama diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: npm install

    - name: Construir la aplicación
      run: npm run build
